#datasets
datasets:
  cub: 
    root: ./data/CUB_200_2011
    split: train
    params:
      img_size: 224
      batch_size: 32
      num_workers: 4
      pin_memory: True
      num_classes: 200


#models
models:
  swin_t:
    force_retrain: False
    params:
      pretrained: True
      freeze: False
      img_size: 224
    optim:
      name: adamw
      lr: 0.00002
      weight_decay: 0.05
      diff_lr: True
      head_lr_multiplier: 10

  efficientnet_v2_s: 
    force_retrain: False
    params:
      pretrained: True
      freeze: False
      img_size: 224
    optim:
      name: adamw
      lr: 0.00002
      weight_decay: 0.05
      diff_lr: True
      head_lr_multiplier: 10
      
#train_options
train:
  epochs: 1
  patience: 7

#checkpoints
checkpoint:
  dir: ./checkpoints

#logs
output:
  dir: outputs/