#datasets
datasets:
  cub: 
    root: ./data/CUB_200_2011
    split: train
    params:
      img_size: 224
      batch_size: 32
      num_workers: 4
      pin_memory: True
      num_classes: 200


#models
models:
  swin_t:
    force_retrain: False
    params:
      optim: adamw
      pretrained: True
      freeze: True
      lr: 0.0005

  efficientnet_v2_s: 
    force_retrain: False
    params:
      optim: adam
      pretrained: True
      freeze: False
      lr: 0.0005

#train_options
train:
  epochs: 1
  patience: 7

#checkpoints
checkpoint:
  dir: ./checkpoints

#logs
output:
  dir: outputs/