dataset:
  name: cub
  root: ./data/CUB_200_2011
  split: train
  params:
    img_size: 224
  batch_size: 32
  num_workers: 4

model:
  name: 'swin_t'
  num_classes: 200
  params:
    pretrained: True
    freeze: False


train:
  epochs: 30
  seed: 42


optim:
 lr: 0.0005



checkpoint:
  dir: ./checkpoints


output:
  dir: outputs/